### ISSUE TITLE
I am getting following if i wan to run kafka meter ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by kausutubh** [BrightTag/kafkameter#17] opened 2017-04-28 12:17 UTC
2017/04/28 17:33:46 INFO  - jmeter.engine.StandardJMeterEngine: Running the test! 
2017/04/28 17:33:46 INFO  - jmeter.samplers.SampleEvent: List of sample_variables: [] 
2017/04/28 17:33:46 INFO  - jmeter.protocol.java.sampler.JavaSampler: Created class: co.signal.kafkameter.KafkaProducerSampler. Uses tearDownTest: true 
2017/04/28 17:33:46 INFO  - jmeter.gui.util.JMeterMenuBar: setRunning(true,*local*) 
2017/04/28 17:33:46 INFO  - jmeter.engine.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group 
2017/04/28 17:33:46 INFO  - jmeter.engine.StandardJMeterEngine: Starting 1 threads for group Thread Group. 
2017/04/28 17:33:46 INFO  - jmeter.engine.StandardJMeterEngine: Thread will continue on error 
2017/04/28 17:33:46 INFO  - jmeter.threads.ThreadGroup: Starting thread group number 1 threads 1 ramp-up 1 perThread 1000.0 delayedStart=false 
2017/04/28 17:33:46 INFO  - jmeter.threads.ThreadGroup: Started thread group number 1 
2017/04/28 17:33:46 INFO  - jmeter.engine.StandardJMeterEngine: All thread groups have been started 
2017/04/28 17:33:46 INFO  - jmeter.threads.JMeterThread: Thread started: Thread Group 1-1 
2017/04/28 17:33:46 FATAL - co.signal.loadgen.LoadGenerator: Exception initializing Load Generator class: co.signal.loadgen.example.TagserveLoadGenerator java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at co.signal.loadgen.LoadGenerator.createGenerator(LoadGenerator.java:67)
	at co.signal.loadgen.LoadGenerator.iterationStart(LoadGenerator.java:57)
	at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:405)
	at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:397)
	at org.apache.jmeter.control.GenericController.next(GenericController.java:158)
	at org.apache.jmeter.control.LoopController.next(LoopController.java:123)
	at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:87)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:239)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Site weights must sum to unity
	at co.signal.loadgen.example.TagserveLoadGenerator.parseSiteWeights(TagserveLoadGenerator.java:126)
	at co.signal.loadgen.example.TagserveLoadGenerator.<init>(TagserveLoadGenerator.java:61)
	... 13 more

2017/04/28 17:33:46 ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at co.signal.loadgen.LoadGenerator.createGenerator(LoadGenerator.java:70)
	at co.signal.loadgen.LoadGenerator.iterationStart(LoadGenerator.java:57)
	at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:405)
	at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:397)
	at org.apache.jmeter.control.GenericController.next(GenericController.java:158)
	at org.apache.jmeter.control.LoopController.next(LoopController.java:123)
	at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:87)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:239)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at co.signal.loadgen.LoadGenerator.createGenerator(LoadGenerator.java:67)
	... 8 more
Caused by: java.lang.RuntimeException: Site weights must sum to unity
	at co.signal.loadgen.example.TagserveLoadGenerator.parseSiteWeights(TagserveLoadGenerator.java:126)
	at co.signal.loadgen.example.TagserveLoadGenerator.<init>(TagserveLoadGenerator.java:61)
	... 13 more

2017/04/28 17:33:46 INFO  - jmeter.threads.JMeterThread: Thread finished: Thread Group 1-1 
2017/04/28 17:33:46 INFO  - jmeter.engine.StandardJMeterEngine: Notifying test listeners of end of test 
2017/04/28 17:33:46 INFO  - jmeter.gui.util.JMeterMenuBar: setRunning(false,*local*) 

Please help me out for this.!!

**Comment by codyaray** [comment] 2017-04-28 12:42
You're running an example class.

```
class: co.signal.loadgen.example.TagserveLoadGenerator
```
If you look for "Caused by" you'll see the error:
```
Caused by: java.lang.RuntimeException: Site weights must sum to unity
```

This error is specific to running the example class. "Unity" is an engineering term meaning "1". In other words, the weights assigned to each site must sum to 1. (The weight is basically saying <weight>% of all requests should go to this site.)

Please read the README and accompanying blog post for more information. http://codyaray.com/2014/07/custom-jmeter-samplers-and-config-elements

**Closed by codyaray** 2017-04-28 12:42 UTC
